os: linux
dist: bionic
language: shell
services:
  - docker
branches:
  only:
    - master
script:
  # install travis cli
  - gem install --no-document travis
  # setup travis shell autocomplete
  - echo "y" | travis --version
  - make deploy-users
  - make rotate-access-keys